<?php

namespace ContainerIO8KyV1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FhF7X8wService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FhF7X8w' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FhF7X8w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'news' => ['privates', '.errored..service_locator.FhF7X8w.App\\Entity\\News', NULL, 'Cannot autowire service ".service_locator.FhF7X8w": it references class "App\\Entity\\News" but no such service exists.'],
        ], [
            'news' => 'App\\Entity\\News',
        ]);
    }
}
