<?php

namespace ContainerIO8KyV1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\EventType' shared autowired service.
     *
     * @return \App\Form\EventType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/EventType.php';

        return $container->privates['App\\Form\\EventType'] = new \App\Form\EventType();
    }
}
