<?php

namespace ContainerIO8KyV1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHobbyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1lcqbNQ.App\Entity\Hobby' shared service.
     *
     * @return \App\Entity\Hobby
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.1lcqbNQ": it references class "App\\Entity\\Hobby" but no such service exists.');
    }
}
