<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIO8KyV1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIO8KyV1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIO8KyV1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIO8KyV1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIO8KyV1\App_KernelDevDebugContainer([
    'container.build_hash' => 'IO8KyV1',
    'container.build_id' => '41a54568',
    'container.build_time' => 1633694618,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIO8KyV1');
