<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::sendEmail'], [], [['text', '/contact']], [], []],
    'event' => [[], ['_controller' => 'App\\Controller\\EventController::list'], [], [['text', '/event']], [], []],
    'create_hobby' => [[], ['_controller' => 'App\\Controller\\HobbyController::create'], [], [['text', '/addHobby']], [], []],
    'edit_hobby' => [['id'], ['_controller' => 'App\\Controller\\HobbyController::edit'], [], [['variable', '-', '[^/]++', 'id', true], ['text', '/editHobby']], [], []],
    'delete_hobby' => [['id'], ['_controller' => 'App\\Controller\\HobbyController::delete'], [], [['variable', '-', '[^/]++', 'id', true], ['text', '/deleteHobby']], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\HomeController::home'], ['lang' => 'de|fr|en'], [['text', '/']], [], []],
    'member' => [[], ['_controller' => 'App\\Controller\\MemberController::index'], [], [['text', '/member']], [], []],
    'news' => [[], ['_controller' => 'App\\Controller\\NewsController::list'], [], [['text', '/news']], [], []],
    'news_detail' => [['id'], ['_controller' => 'App\\Controller\\NewsController::detail'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/news']], [], []],
    'create_news' => [[], ['_controller' => 'App\\Controller\\NewsController::createNews'], [], [['text', '/addNews']], [], []],
    'edit_news' => [['id'], ['_controller' => 'App\\Controller\\NewsController::update'], [], [['variable', '-', '[^/]++', 'id', true], ['text', '/editNews']], [], []],
    'delete_news' => [['id'], ['_controller' => 'App\\Controller\\NewsController::delete'], [], [['variable', '-', '[^/]++', 'id', true], ['text', '/deleteNews']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
