<?php

namespace ContainerPFoKqX9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FhF7X8w.App\Entity\News' shared service.
     *
     * @return \App\Entity\News
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.FhF7X8w": it references class "App\\Entity\\News" but no such service exists.');
    }
}
